"""Turn a raster widget in public/icons into a React component.

The source files are SVG wrappers around a base64 PNG sitting on a pale blue
page: they carry a background the board doesn't want, dead margin that makes the
art render small, and megabytes of weight. This pulls the bitmap out, removes
the background, trims to the artwork, re-encodes it and writes a component with
the image embedded, so the widget is self-contained and identical to the source.

    python tools/build-widgets/build.py 1:CentrifugalPump:"Centrifugal Pump"

Writes components/icons/<Name>.tsx and prints the registry lines to add.
"""

import base64
import io
import pathlib
import re
import sys
from collections import deque

import numpy as np
from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parents[2]
ICONS = ROOT / "public" / "icons"
OUT_DIR = ROOT / "components" / "icons"

# Longest edge of the stored art. The board renders widgets between 70px and a
# few hundred, so this leaves generous headroom for zooming without the weight
# of the full-resolution original.
MAX_EDGE = 1100
# WebP quality. 90 is visually indistinguishable from the source here while
# costing roughly a twentieth of the original PNG.
QUALITY = 90


def extract_raster(name: str) -> Image.Image:
    """Pull the embedded bitmap out of an SVG wrapper, or open a plain image."""
    for suffix in (".svg", ".png", ".jpg", ".jpeg", ".webp"):
        path = ICONS / f"{name}{suffix}"
        if not path.exists():
            continue
        if suffix != ".svg":
            return Image.open(path)
        markup = path.read_text(encoding="utf-8", errors="replace")
        match = re.search(r'href="data:image/(?:png|jpeg);base64,([^"]+)"', markup)
        if not match:
            raise SystemExit(f"{path.name} has no embedded raster")
        return Image.open(io.BytesIO(base64.b64decode(match.group(1))))
    raise SystemExit(f"no source image found for {name!r} in {ICONS}")


def strip_background(im: Image.Image, flood_tol: int = 38, halo_tol: int = 26):
    """Clear the page background.

    Flooding inward from the corners protects light areas enclosed by the
    drawing, which a plain colour match would punch holes in. A second pass then
    clears the anti-aliased halo the flood leaves around the artwork, which is
    what otherwise shows up as a pale fringe on a coloured board.
    """
    im = im.convert("RGBA")
    w, h = im.size
    px = im.load()
    seeds = [(0, 0), (w - 1, 0), (0, h - 1), (w - 1, h - 1)]
    refs = [px[x, y][:3] for x, y in seeds]

    def near(c, tol):
        return any(
            abs(c[0] - r[0]) + abs(c[1] - r[1]) + abs(c[2] - r[2]) <= tol for r in refs
        )

    seen = bytearray(w * h)
    queue = deque()
    for x, y in seeds:
        queue.append((x, y))
        seen[y * w + x] = 1
    while queue:
        x, y = queue.popleft()
        if not near(px[x, y][:3], flood_tol):
            continue
        px[x, y] = (255, 255, 255, 0)
        for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            nx, ny = x + dx, y + dy
            if 0 <= nx < w and 0 <= ny < h and not seen[ny * w + nx]:
                seen[ny * w + nx] = 1
                queue.append((nx, ny))

    pixels = np.array(im).astype(np.int16)
    rgb, alpha = pixels[..., :3], pixels[..., 3]
    halo = np.zeros(alpha.shape, dtype=bool)
    for ref in refs:
        halo |= np.abs(rgb - np.array(ref, dtype=np.int16)).sum(-1) <= halo_tol
    pixels[halo & (alpha > 0)] = [255, 255, 255, 0]
    return Image.fromarray(pixels.astype(np.uint8), "RGBA")


def fit(im: Image.Image) -> Image.Image:
    """Trim to the artwork so it fills its own box, then cap the long edge."""
    box = im.getbbox()
    if box:
        im = im.crop(box)
    if max(im.size) > MAX_EDGE:
        scale = MAX_EDGE / max(im.size)
        im = im.resize(
            (max(1, round(im.width * scale)), max(1, round(im.height * scale))),
            Image.LANCZOS,
        )
    return im


def encode(im: Image.Image) -> tuple[str, int]:
    buf = io.BytesIO()
    im.save(buf, "WEBP", quality=QUALITY, method=6, exact=True)
    raw = buf.getvalue()
    return base64.b64encode(raw).decode("ascii"), len(raw)


def component_source(component: str, label: str, im: Image.Image, data: str) -> str:
    return f'''"use client";

import type {{ ImgHTMLAttributes }} from "react";

/**
 * {label} — the original artwork with its page background removed and the
 * margin trimmed away, re-encoded as WebP and embedded here so the widget is
 * self-contained.
 *
 * The image is the source pixels, so it matches the original exactly. It is a
 * bitmap rather than paths: sized for the board at up to {MAX_EDGE}px on its
 * long edge, which is well beyond what a node ever renders at.
 *
 * Generated by tools/build-widgets — re-running overwrites this file.
 */
const ART =
  "data:image/webp;base64,{data}";

export const WIDTH = {im.width};
export const HEIGHT = {im.height};

export interface {component}Props
  extends Omit<ImgHTMLAttributes<HTMLImageElement>, "src"> {{
  alt?: string;
}}

export function {component}({{ alt = "{label}", ...props }}: {component}Props) {{
  // next/image cannot optimise a data URI, and the art is already WebP-encoded
  // and sized for the board, so a plain <img> is the right element here.
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img src={{ART}} alt={{alt}} width={{WIDTH}} height={{HEIGHT}} draggable={{false}} {{...props}} />
  );
}}
'''


def main(specs: list[str]) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    built = []
    for spec in specs:
        name, component, *rest = spec.split(":")
        label = ":".join(rest) or component
        im = fit(strip_background(extract_raster(name)))
        data, size = encode(im)
        source = component_source(component, label, im, data)
        (OUT_DIR / f"{component}.tsx").write_text(source, encoding="utf-8")
        original = (ICONS / f"{name}.svg").stat().st_size
        print(
            f"{component:<20} {im.width}x{im.height}  "
            f"webp={size / 1024:.0f}KB  tsx={len(source) / 1024:.0f}KB  "
            f"(source was {original / 1024:.0f}KB)"
        )
        built.append((name, component, label))

    print("\nAdd to lib/convertedWidgets.ts:")
    for name, component, label in built:
        key = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", component).lower()
        print(f'  {{ key: "{key}", file: "{name}.svg", label: "{label}" }},')
    print("\nAnd register the component in components/icons/registry.ts.")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)
    main(sys.argv[1:])
