import type {
  FeederKpiRow,
  OutageFiltersConfig,
  OutageKpiTile,
  OutageRow,
  RecentlyRestoredRow,
  SelectedOutageDetailsConfig,
  TopPssRow,
} from "./types";
import type { NavBarConfig } from "../widgets/NavBar/types";
import type { PageHeaderConfig } from "../widgets/PageHeader/types";

export const OUTAGE_NAVBAR: NavBarConfig = {
  brand: "AUTRIXA",
  brandSuperscript: "TM",
  brandSubtitle: "Distribution SCADA",
  navItems: [
    { id: "home", label: "Home", icon: "home" },
    { id: "network", label: "Network", icon: "network" },
    { id: "pss", label: "PSS", icon: "pss" },
    { id: "alarms", label: "Alarms", icon: "alarms", badge: "12" },
    { id: "events", label: "Events", icon: "events" },
    { id: "reports", label: "Reports", icon: "reports" },
    { id: "trends", label: "Trends", icon: "trends" },
    { id: "settings", label: "Settings", icon: "settings" },
  ],
  dateTime: "09 Sep 2026 14:28:36",
  operatorLabel: "Operator",
  operatorValue: "admin",
  logoutLabel: "Logout",
  showLogout: true,
  partnerBrand: "RS Consultancy",
  partnerTagline: "Reliable | Scalable | Connected",
};

export const OUTAGE_PAGE_HEADER: PageHeaderConfig = {
  breadcrumb: ["Home", "Outage Monitoring"],
  title: "OUTAGE MONITORING",
  subtitle: "Real-time feeder outage detection, monitoring and restoration tracking",
  scopeTags: ["Total PSS 400", "System Status: All PSS Connected"],
  liveDataLabel: "09-Sep-2026",
  showLiveData: true,
};

export const OUTAGE_KPI_TILES: OutageKpiTile[] = [
  {
    id: "kpi-active",
    label: "Active Outages",
    value: "8",
    icon: "alert-red",
    colorScheme: "red",
  },
  {
    id: "kpi-restored",
    label: "Restored Feeders",
    value: "24",
    subtext: "(Today)",
    icon: "check-green",
    colorScheme: "green",
  },
  {
    id: "kpi-total",
    label: "Total Outages Today",
    value: "32",
    trend: "up",
    subtext: "Yesterday: 28",
    icon: "doc-blue",
    colorScheme: "blue",
  },
  {
    id: "kpi-avg-duration",
    label: "Average Outage Duration",
    value: "1 h 24 m",
    trend: "down",
    subtext: "Yesterday: 1 h 58 m",
    icon: "clock-blue",
    colorScheme: "blue",
  },
  {
    id: "kpi-longest",
    label: "Longest Outage",
    value: "6 h 12 m",
    subtext: "RATANPUR PSS Feeder 03",
    icon: "stopwatch-red",
    colorScheme: "red",
  },
  {
    id: "kpi-last-time",
    label: "Last Outage Time",
    value: "14:12",
    subtext: "09-Sep-2026",
    icon: "calendar-blue",
    colorScheme: "blue",
  },
  {
    id: "kpi-tripped",
    label: "Feeders Tripped",
    value: "11",
    subtext: "(Today)",
    icon: "bolt-orange",
    colorScheme: "red",
  },
  {
    id: "kpi-open",
    label: "Feeders Open",
    value: "5",
    subtext: "(Today)",
    icon: "breaker-blue",
    colorScheme: "red",
  },
];

export const OUTAGE_ROWS: OutageRow[] = [
  {
    id: "out-1",
    num: 1,
    pss: "KANKANPURA PSS",
    feeder: "Feeder 03",
    outageStart: "09-Sep-2026 14:12",
    outageEnd: "—",
    outageDuration: "0 h 16 m",
    breakerStatus: "Tripped",
    tripCause: "Overcurrent",
    restorationTime: "—",
    operatorRemarks: "Auto trip - under investigation",
    status: "Active",
  },
  {
    id: "out-2",
    num: 2,
    pss: "BILASPUR PSS",
    feeder: "Feeder 01",
    outageStart: "09-Sep-2026 13:46",
    outageEnd: "—",
    outageDuration: "0 h 42 m",
    breakerStatus: "Open",
    tripCause: "Earth Fault",
    restorationTime: "—",
    operatorRemarks: "Patrolling team dispatched",
    status: "Active",
  },
  {
    id: "out-3",
    num: 3,
    pss: "RAIPUR PSS",
    feeder: "Feeder 05",
    outageStart: "09-Sep-2026 12:21",
    outageEnd: "09-Sep-2026 13:58",
    outageDuration: "1 h 37 m",
    breakerStatus: "Closed",
    tripCause: "Overcurrent",
    restorationTime: "09-Sep-2026 13:58",
    operatorRemarks: "Fault cleared, supply restored",
    status: "Restored",
  },
  {
    id: "out-4",
    num: 4,
    pss: "DURG PSS",
    feeder: "Feeder 02",
    outageStart: "09-Sep-2026 11:05",
    outageEnd: "09-Sep-2026 12:10",
    outageDuration: "1 h 05 m",
    breakerStatus: "Closed",
    tripCause: "Unknown",
    restorationTime: "09-Sep-2026 12:10",
    operatorRemarks: "Manual close after patrolling",
    status: "Restored",
  },
  {
    id: "out-5",
    num: 5,
    pss: "BHILAI PSS",
    feeder: "Feeder 04",
    outageStart: "09-Sep-2026 10:32",
    outageEnd: "—",
    outageDuration: "3 h 56 m",
    breakerStatus: "Open",
    tripCause: "Line Fault",
    restorationTime: "—",
    operatorRemarks: "Line under repair",
    status: "Critical",
  },
  {
    id: "out-6",
    num: 6,
    pss: "KANKANPURA PSS",
    feeder: "Feeder 01",
    outageStart: "09-Sep-2026 09:18",
    outageEnd: "09-Sep-2026 10:05",
    outageDuration: "0 h 47 m",
    breakerStatus: "Closed",
    tripCause: "Overcurrent",
    restorationTime: "09-Sep-2026 10:05",
    operatorRemarks: "Reclosed successfully",
    status: "Restored",
  },
  {
    id: "out-7",
    num: 7,
    pss: "BILASPUR PSS",
    feeder: "Feeder 03",
    outageStart: "09-Sep-2026 08:55",
    outageEnd: "09-Sep-2026 09:40",
    outageDuration: "0 h 45 m",
    breakerStatus: "Closed",
    tripCause: "Equipment Fault",
    restorationTime: "09-Sep-2026 09:40",
    operatorRemarks: "Transformer side issue",
    status: "Restored",
  },
  {
    id: "out-8",
    num: 8,
    pss: "RAIPUR PSS",
    feeder: "Feeder 02",
    outageStart: "09-Sep-2026 07:12",
    outageEnd: "—",
    outageDuration: "7 h 16 m",
    breakerStatus: "Tripped",
    tripCause: "Overcurrent",
    restorationTime: "—",
    operatorRemarks: "High fault current - critical",
    status: "Critical",
  },
  {
    id: "out-9",
    num: 9,
    pss: "DURG PSS",
    feeder: "Feeder 06",
    outageStart: "09-Sep-2026 05:48",
    outageEnd: "09-Sep-2026 06:32",
    outageDuration: "0 h 44 m",
    breakerStatus: "Closed",
    tripCause: "Earth Fault",
    restorationTime: "09-Sep-2026 06:32",
    operatorRemarks: "Patrolling completed",
    status: "Restored",
  },
  {
    id: "out-10",
    num: 10,
    pss: "BHILAI PSS",
    feeder: "Feeder 01",
    outageStart: "09-Sep-2026 03:21",
    outageEnd: "09-Sep-2026 04:15",
    outageDuration: "0 h 54 m",
    breakerStatus: "Closed",
    tripCause: "Scheduled",
    restorationTime: "09-Sep-2026 04:15",
    operatorRemarks: "Maintenance completed",
    status: "Restored",
  },
];

export const FEEDER_KPI_ROWS: FeederKpiRow[] = [
  {
    id: "fkpi-1",
    num: 1,
    feeder: "Feeder 03",
    outageCount: 6,
    totalDuration: "13 h 24 m",
    avgDuration: "2 h 14 m",
    longestOutage: "6 h 12 m",
    lastOutage: "09-Sep 14:12",
  },
  {
    id: "fkpi-2",
    num: 2,
    feeder: "Feeder 02",
    outageCount: 5,
    totalDuration: "8 h 36 m",
    avgDuration: "1 h 43 m",
    longestOutage: "4 h 05 m",
    lastOutage: "09-Sep 07:12",
  },
  {
    id: "fkpi-3",
    num: 3,
    feeder: "Feeder 01",
    outageCount: 4,
    totalDuration: "6 h 21 m",
    avgDuration: "1 h 35 m",
    longestOutage: "3 h 10 m",
    lastOutage: "09-Sep 10:05",
  },
  {
    id: "fkpi-4",
    num: 4,
    feeder: "Feeder 05",
    outageCount: 3,
    totalDuration: "4 h 18 m",
    avgDuration: "1 h 26 m",
    longestOutage: "2 h 50 m",
    lastOutage: "09-Sep 12:21",
  },
  {
    id: "fkpi-5",
    num: 5,
    feeder: "Feeder 04",
    outageCount: 3,
    totalDuration: "4 h 12 m",
    avgDuration: "1 h 24 m",
    longestOutage: "3 h 56 m",
    lastOutage: "09-Sep 10:32",
  },
];

export const RECENTLY_RESTORED_ROWS: RecentlyRestoredRow[] = [
  {
    id: "rec-1",
    num: 1,
    feeder: "Feeder 05",
    restoredTime: "09-Sep-2026 13:58",
    outageDuration: "1 h 37 m",
    remarks: "Supply restored",
  },
  {
    id: "rec-2",
    num: 2,
    feeder: "Feeder 02",
    restoredTime: "09-Sep-2026 12:10",
    outageDuration: "1 h 05 m",
    remarks: "Manual close",
  },
  {
    id: "rec-3",
    num: 3,
    feeder: "Feeder 01",
    restoredTime: "09-Sep-2026 10:05",
    outageDuration: "0 h 47 m",
    remarks: "Reclosed",
  },
  {
    id: "rec-4",
    num: 4,
    feeder: "Feeder 03",
    restoredTime: "09-Sep-2026 09:40",
    outageDuration: "0 h 45 m",
    remarks: "Fault cleared",
  },
  {
    id: "rec-5",
    num: 5,
    feeder: "Feeder 06",
    restoredTime: "09-Sep-2026 06:32",
    outageDuration: "0 h 44 m",
    remarks: "Patrolling completed",
  },
];

export const TOP_PSS_ROWS: TopPssRow[] = [
  {
    id: "tpss-1",
    num: 1,
    pss: "KANKANPURA",
    outageCount: 8,
    totalDuration: "18 h 12 m",
  },
  {
    id: "tpss-2",
    num: 2,
    pss: "RAIPUR",
    outageCount: 7,
    totalDuration: "15 h 36 m",
  },
  {
    id: "tpss-3",
    num: 3,
    pss: "BILASPUR",
    outageCount: 6,
    totalDuration: "11 h 24 m",
  },
  {
    id: "tpss-4",
    num: 4,
    pss: "DURG",
    outageCount: 6,
    totalDuration: "10 h 52 m",
  },
  {
    id: "tpss-5",
    num: 5,
    pss: "BHILAI",
    outageCount: 5,
    totalDuration: "9 h 18 m",
  },
];

export const DEFAULT_OUTAGE_FILTERS: OutageFiltersConfig = {
  title: "Filters",
  dateRangeLabel: "Date Range",
  dateFromValue: "09-Sep-2026",
  dateToValue: "09-Sep-2026",
  pssLabel: "PSS",
  pssValue: "All PSS (400)",
  pssOptions: ["All PSS (400)", "KANKANPURA PSS", "BILASPUR PSS", "RAIPUR PSS", "DURG PSS", "BHILAI PSS"],
  feederLabel: "Feeder",
  feederValue: "All Feeders",
  feederOptions: ["All Feeders", "Feeder 01", "Feeder 02", "Feeder 03", "Feeder 04", "Feeder 05", "Feeder 06"],
  statusLabel: "Status",
  statusValue: "All (Active, Restored, Critical)",
  statusOptions: ["All (Active, Restored, Critical)", "Active", "Restored", "Critical"],
  tripCauseLabel: "Trip Cause",
  tripCauseValue: "All Causes",
  tripCauseOptions: ["All Causes", "Overcurrent", "Earth Fault", "Line Fault", "Equipment Fault", "Unknown", "Scheduled"],
  applyButtonLabel: "Apply Filter",
  resetButtonLabel: "Reset",
};

export const DEFAULT_SELECTED_OUTAGE_DETAILS: SelectedOutageDetailsConfig = {
  title: "Selected Outage Details",
  rows: [
    { id: "s1", label: "PSS", value: "KANKANPURA PSS" },
    { id: "s2", label: "Feeder", value: "Feeder 03" },
    { id: "s3", label: "Outage Start", value: "09-Sep-2026 14:12:36" },
    { id: "s4", label: "Outage End", value: "—" },
    { id: "s5", label: "Outage Duration", value: "0 h 16 m" },
    { id: "s6", label: "Breaker Status", value: "Tripped", isBreakerStatus: true },
    { id: "s7", label: "Trip Cause", value: "Overcurrent" },
    { id: "s8", label: "Restoration Time", value: "—" },
    { id: "s9", label: "Operator Remarks", value: "Auto trip - under investigation" },
    { id: "s10", label: "Communication", value: "Good (RTU Online)", isDotIndicator: true, dotColor: "green" },
    { id: "s11", label: "Data Quality", value: "Good", isDotIndicator: true, dotColor: "green" },
    { id: "s12", label: "Status", value: "Active", isStatusBadge: true },
  ],
};
